FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN addgroup -g 1001 -S nodejs
RUN adduser -S vuejs -u 1001
RUN chown -R vuejs:nodejs /app
USER vuejs
EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]